### ISSUE TITLE
crypto deprecation

### ISSUE THREAD

**Issue by sandro-pasquali** [colinskow/superlogin#125] opened 2016-12-09 19:08 UTC
After a /register action I see the following in stdout:

`(node:9672) DeprecationWarning: crypto.pbkdf2 without specifying a digest is deprecated. Please specify a digest`

Using Node 6.9.2

Just wondering if this is something to keep in mind/fix

**Comment by colinskow** [comment] 2016-12-21 12:27
Yes, this will likely break in Node 7. The library I'm using is unmaintained so it needs to be forked and `SHA1` needs to be specified as the digest.

**Comment by colinskow** [comment] 2016-12-21 12:28
This is a duplicate of #64 so closing.

**Closed by colinskow** 2016-12-21 12:28 UTC
