### ISSUE TITLE
Multiple logins by single user in CouchDB

### ISSUE THREAD

**Issue by christianmccormick** [colinskow/superlogin#68] opened 2016-05-13 18:02 UTC
I am developing a mobile app with a web app counterpart. Due to the nature of the apps users should be able to remain logged in on the mobile app and web app simultaneously. I was previously doing this using Superlogin and Cloudant with no issue, however after switching back to CouchDB I am now unable to keep users logged in across multiple apps. Upon logging in to the web app users are immediately logged out of the mobile app (changes feed and all other requests begin to return 401 responses) and visa versa. It appears that only one valid session is being permitted at a time.

Is there a configuration setting that permits multiple sessions when using CouchDB (not Cloudant)? I looked through the Superlogin docs but could not find anything relevant.

**Comment by christianmccormick** [comment] 2016-05-13 18:15
After further testing I determined that my issue was due to the login cleaning up expired tokens. On a side note, I find it odd that I did not encounter this behavior when on Cloudant, but only when using CouchDB. Perhaps this discrepancy is worth looking into further?

**Comment by colinskow** [comment] 2016-05-13 18:42
You should be able to have multiple sessions on either platform. If the session token is not long enough for your needs, you can adjust the length in the config.

If you can confirm that there is a bug and figure out exact steps to reproduce it, I would be happy to take a look into it.

**Comment by colinskow** [comment] 2016-05-15 23:26
Since we don't know if this is a real bug or how to reproduce it, I am closing for now. If you can confirm and reproduce it feel free to open again.

**Closed by colinskow** 2016-05-15 23:26 UTC
Labels: needs reproducing, possible bug
